from fastapi import APIRouter, Depends, status, Request
from sqlalchemy.ext.asyncio import AsyncSession
from app.db.base import get_db_session , get_common_db

from app.schemas.ai_schemas import (
    GenerateMessageRequest,
    GenerateMessageResponse
)
from app.core.constants import AVAILABLE_PROVIDERS
from app.services.ai_message_service import AIMessageService
from app.core.logging_config import get_logger

logger = get_logger(__name__)

router = APIRouter(prefix="/ai", tags=["AI"])

ai_service = AIMessageService()


@router.get("/models")
async def list_llm_models():
    """
    Return available providers and models.
    """
    return AVAILABLE_PROVIDERS


@router.post(
    "/generate-message",
    response_model=GenerateMessageResponse,
    status_code=status.HTTP_200_OK
)
async def generate_message(
    request: Request,
    payload: GenerateMessageRequest,
    db: AsyncSession = Depends(get_common_db)
):
    """
    Generate professional message using tenant AI configuration.
    """

    tenant_id = getattr(request.state, "tenant_id", None)
    user_id = getattr(request.state, "user_id", None)

    generated_message = await ai_service.generate_message(
        db=db,
        tenant_id=tenant_id,
        message=payload.message
    )

    logger.info(
        f"AI message generated by user {user_id} for tenant {tenant_id}"
    )

    return GenerateMessageResponse(
        generated_message=generated_message ,
        old_message=payload.message
    )


@router.post(
    "/regenerate-message",
    response_model=GenerateMessageResponse,
    status_code=status.HTTP_200_OK
)
async def regenerate_message(
    request: Request,
    payload: GenerateMessageRequest,
    db: AsyncSession = Depends(get_common_db)
):
    """
    Regenerate message using prompt template.
    """

    tenant_id = getattr(request.state, "tenant_id", None)
    user_id = getattr(request.state, "user_id", None)

    generated_message = await ai_service.regenerate_message(
        db=db,
        tenant_id=tenant_id,
        message=payload.message,
        prompt_key="professional_message"
    )

    logger.info(
        f"AI message regenerated by user {user_id} for tenant {tenant_id}"
    )

    return GenerateMessageResponse(
        generated_message=generated_message , 
        old_message=payload.message
    )